#ifndef MOM_IDS_INCLUDED
#define MOM_IDS_INCLUDED

namespace MOM_IDs {

//Object IDs.
enum ObjectIDs : short
{
	GALAXY_SHRINKING_PLATFORM = 0x0200,
	SILVER_COIN,
	INVISIBLE_WALL,
	BERRY,
	YOSHI_RIDE,
	OBJECT_LIGHTING_MODIFIER,
	TWO_DEE_LEVEL,
	TWO_DEE_CAMERA_LIMITER,
	COLORED_GOOMBA_SMALL,
	COLORED_GOOMBA,
	COLORED_GOOMBA_LARGE,
	TOXIC_LEVEL,
	NOTEBLOCK,
	SHY_GUY,
	LAUNCH_STAR,
	KAMEK_SHOT,
	KAMEK, //210
	KAMELLA,
	SKYBOX_ROTATOR,
	FALLING_ICICLE,
	GRAVITY_MODIFIER,
	COLORED_GOOMBA_2_SMALL,
	COLORED_GOOMBA_2,
	COLORED_GOOMBA_2_LARGE,
	YOSHI_NPC,
	COLORED_PIPE,
	CHARACTER_BLOCK,
	TREE_SHADOW,
	SAVE_BLOCK,
	STAR_CHIP,
	DOOR_BLOCKER,
	COLORED_COIN,
	COLORED_TOAD_NPC, //220
	PEACH_NPC,
	BLUE_ICE_BLOCK,
	MEGA_BLOCK,
	CUTSCENE_LOADER,
	CUSTOM_BLOCK,
	TREASURE_CHEST,
	THWOMP,
	MAGMA_THWOMP,
	GIGA_THWOMP,
	PENGUIN_NPC,
	BABY_PENGUIN_NPC,
	FFL_SPECIFICS,
	RABBIT_NPC,

	END_OF_MOM_OBJ_IDS,

	ICE_COIN_COUNTER = 564 // was added later
};

//constexpr short int CONDITIONAL_CUTSCENE_LOADER_ID = 0x0165;

//Assets.
enum AssetIDs : short
{
	GALAXY_SHRINKING_PLATFORM_FRAME_MODEL_ID, //0
	GALAXY_SHRINKING_PLATFORM_MODEL_ID,
	GALAXY_SHRINKING_PLATFORM_COLLISION_ID,
	SILVER_COIN_MODEL_ID,
	INVISIBLE_WALL_MODEL_ID,
	INVISIBLE_WALL_COLLISION_ID,
	BERRY_MODEL_ID,
	BERRY_STEM_MODEL_ID,
	YOSHI_RIDE_ANIM_ID,
	COLORED_GOOMBA_MODEL_ID,
	COLORED_GOOMBA_TEXSEQ_ID,
	NOTEBLOCK_MODEL_ID,
	NOTEBLOCK_COLLISION_ID,
	SHY_GUY_MODEL_ID,
	SHY_GUY_WAIT_ANIM_ID,
	SHY_GUY_WALK_ANIM_ID,
	SHY_GUY_RUN_ANIM_ID, //10
	SHY_GUY_FREEZE_ANIM_ID,
	LAUNCH_STAR_MODEL_ID,
	LAUNCH_STAR_WAIT_ANIM_ID,
	LAUNCH_STAR_LAUNCH_ANIM_ID,
	KAMEK_MODEL_ID,
	KAMELLA_MODEL_ID,
	KAMEK_APPEAR_ANIM_ID,
	KAMEK_WAVE_ANIM_ID,
	KAMEK_SHOOT_ANIM_ID,
	KAMEK_POOF_ANIM_ID,
	KAMEK_WAIT_ANIM_ID,
	KAMEK_HURT_ANIM_ID,
	KAMEK_DEFEAT_ANIM_ID,
	KAMEK_MAGIC_PARTICLE_TEXTURE_ID,
	UNUSED_ID_1F,
	ICICLE_MODEL_ID, //20
	YOSHI_NPC_MODEL_ID,
	YOSHI_NPC_ANIM_ID,
	COLORED_PIPE_MODEL_ID,
	COLORED_PIPE_COLLISION_ID,
	CHARACTER_BLOCK_MODEL_ID,
	CHARACTER_BLOCK_TEXANIM_ID,
	CHARACTER_BLOCK_COLLSION_ID,
	CHARACTER_BLOCK_TRANSPARENT_MODEL_ID,
	CHARACTER_BLOCK_TRANSPARENT_TEXANIM_ID,
	CHARACTER_BLOCK_TRANSPARENT_MARK_TEXANIM_ID,
	CHARACTER_BLOCK_TRANSPARENT_ANIMATION_ID,
	UNUSED_ID_2C,
	UNUSED_ID_2D,
	UNUSED_ID_2E,
	UNUSED_ID_2F,
	SAVE_BLOCK_MODEL_ID, //30
	SAVE_BLOCK_ANIM_ID,
	SAVE_BLOCK_COLLISION_ID,
	STAR_CHIP_MODEL_ID,
	DOOR_BLOCKER_MODEL_ID,
	DOOR_BLOCKER_COLLISION_ID,
	COLORED_COIN_MODEL_ID,
	COLORED_TOAD_NPC_MODEL_ID,
	COLORED_TOAD_NPC_TEXANIM_ID,
	COLORED_TOAD_NPC_ANIM_1_ID,
	COLORED_TOAD_NPC_ANIM_2_ID,
	PEACH_NPC_MODEL_ID,
	PEACH_NPC_ANIM_1_ID,
	PEACH_NPC_ANIM_2_ID,
	BLUE_ICE_BLOCK_MODEL_ID,
	BLUE_ICE_BLOCK_COLLISION_ID,
	MEGA_BLOCK_MODEL_ID, //40
	MEGA_BLOCK_COLLISION_ID,
	YELLOW_BLOCK_MODEL_ID,
	RED_BLOCK_MODEL_ID,
	RED_BLOCK_TRANSPARENT_MODEL_ID,
	BLOCK_COLLISION_ID,
	RED_BLOCK_TRANSPARENT_ANIMATION_ID,
	TREASURE_CHEST_MODEL_ID,
	TREASURE_CHEST_ANIM_ID,
	THWOMP_MODEL_ID,
	THWOMP_TEXANIM_ID,
	THWOMP_COLLISION_ID,
	MAGMA_THWOMP_MODEL_ID,
	GIGA_THWOMP_MODEL_ID,
	GIGA_THWOMP_COLLISION_ID,
	PENGUIN_MODEL_ID,
	PENGUIN_ANIM_ID, // 50
	BABY_PENGUIN_MODEL_ID,
	FFL_CUTSCENE_ID,
	UNUSED_ID_53, // COLORED_GOOMBA_MODEL_2_ID,
	RABBIT_MODEL_ID,
	RABBIT_TEXANIM_ID,
	RABBIT_ANIM_ID
};

} // namespace MOM_IDs

#endif
